steps:

    - id: "Running TEST"
      name: 'https://hub.docker.com/_/golang'
      args: ['test','-timeout','30s','-run','^TestSum1$']  
    
    - id: "Running Build"
      name: 'https://hub.docker.com/_/golang'
      args: ['build','-ldflags','"-s -w"','--buildmode=exe','-o','main']  
    
    - id: "Building Image"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build','.']
    
    - id: "Pushing Image"
      name: 'gcr.io/cloud-builders/docker'
      args: ['push','$PROJECT_ID/go-ci-sample']
